# Generated by Django 2.2.24 on 2022-09-03 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_pokemon_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='parent',
            new_name='previous_evolution',
        ),
    ]
